### ISSUE TITLE
Pfade in "background: url(...)" werden nicht angepasst.

### ISSUE THREAD

**Issue by vaxul** [kaystrobach/TYPO3.dyncss_less#1]
EDIT
Ich denke, dass dieses Issue wohl doch bei "dyncss" einsortiert werden sollte.
/EDIT

**Testsystem:**
TYPO3 CMS v4.6.18 mit dyncss v0.2.6 und dyncss_less v0.2.5

**Ein Beispielausschnitt**

Ausgangsdatei styles.less:

``` css
.button-style {
    display: block;
    background: url(../design-images/button-sprite.png) 0 0 no-repeat;
    cursor: pointer;
    font-weight: 700;
    font-family: Arial, Helvetica, sans-serif;
    text-decoration: none;
    text-transform: uppercase;
}
```

style.less-982ba536-a253e820-fc7495da.less:

``` css
.button-style {
    display: block;
    background: url(../design-images/button-sprite.png) 0 0 no-repeat;
    cursor: pointer;
    font-weight: 700;
    font-family: Arial, Helvetica, sans-serif;
    text-decoration: none;
    text-transform: uppercase;
}
```

style.less-982ba536-a253e820-fc7495da.cache:

``` css
.button-style {
  display: block;
  background: url(../design-images/button-sprite.png) 0 0 no-repeat;
  cursor: pointer;
  font-weight: 700;
  font-family: Arial, Helvetica, sans-serif;
  text-decoration: none;
  text-transform: uppercase;
}
```

Enddatei style.less-982ba536-a253e820-fc7495da.css

``` css
.button-style {
  display: block;
  background: url(../design-images/button-sprite.png) 0 0 no-repeat;
  cursor: pointer;
  font-weight: 700;
  font-family: Arial, Helvetica, sans-serif;
  text-decoration: none;
  text-transform: uppercase;
}
```

Bei weiteren Fragen stehe ich zur Verfügung. ;)
